### ISSUE TITLE
Run locally and receive telegram notifications

### ISSUE THREAD

**Issue by juancash** [kuznetsov-m/huobi-spot-order-notification#1]
Hi!

Great project !!!

Could you give some instructions how to run locally ?

I have running locally a similar project for Binance, but i'ts in node.

Thanks.

**Comment by juancash** [comment]
I was able to execute it locally. I followed this steps:

1. Install python3
2. Install poetry
3. Install project dependencies, run this command into the project root directory:
`poetry install`
4. Set environment variables
5. Run the project with:
`poetry run python3 main.py`

Now, I receive the message "Bot restarted" on my telegram chat, but when I create or cancel an order on Huobi, I don't receive nothing.

**Comment by kuznetsov-m** [comment]
Hi! Thanks for checking out this project!
The steps described above in this topic are correct. Looks like project is running.
Please show the console log after starting the project. Are you getting messages that huobi client is connected?

```
huobi-client - INFO - [Sub][1] Connecting...
huobi-client - INFO - [Sub][1] Connected to server
```

**Comment by juancash** [comment]
Hi!
sorry for the delay in response.
Today I was able to test again. I was testing stop-limit orders. 
I think that for now the project only works with limit orders since with those it has worked correctly.
Thanks and great job!!!
